name: Run unit tests & check conventions

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    container:
      image: "ubuntu:20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: |
          apt-get update && apt-get install -y sudo
          sudo apt install -y git
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
          sudo apt-get install -y gcc g++ make
          
          sudo apt install -y curl dirmngr apt-transport-https lsb-release ca-certificates vim
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -

          sudo apt-get install -y nodejs
          npm install @commitlint/config-conventional
          sudo npm install -g yarn
          yarn add --dev jest typescript ts-jest @types/jest
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Run tests to validate our plugins
        run: yarn jest

  sanitycheck:
    runs-on: ubuntu-20.04
    container:
      image: "ubuntu:20.04"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # needed because of commit-lint, see https://github.com/conventional-changelog/commitlint/issues/3376
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          apt-get update && apt-get install -y sudo
          sudo apt install -y git
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
          sudo apt-get install -y gcc g++ make
          
          sudo apt install -y curl dirmngr apt-transport-https lsb-release ca-certificates vim
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -

          sudo apt-get install -y nodejs
      - name: Install commitlint
        run: npm install @commitlint/config-conventional
      - name: Validate current commit (last commit) with commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

